### ISSUE TITLE
Uncaught (in promise) TypeError: Request failed

### ISSUE THREAD

**Issue by sydev** [jakearchibald/simple-serviceworker-tutorial#12]
A picture says more than a thousands words.

<img width="838" alt="Request failed" src="https://cloud.githubusercontent.com/assets/11978927/20461971/184e796a-af0f-11e6-81c2-87cb097e981a.png">

I just installed with `npm install` and started it with `npm start`. The error occurs immediatly.

**Comment by davicrystal** [comment]
In sw.js I commented the line:

`//  new Request('https://farm6.staticflickr.com/5594/14749918329_888df4f2ef.jpg', {mode: 'no-cors'})`

After that it will work

**Comment by jakearchibald** [comment]
Ah, good catch. The behaviour of `addAll` changed in the spec.

**Comment by NewDc** [comment]
how to fixed?

**Comment by ravo10** [comment]
This happend to me when I had some URL's that I wanted to cache, that did not exist.

**Comment by chaos67731** [comment]
@ravo10 Thanks, this fixed it for me!

**Comment by marcelovue** [comment]
I changed 
``let filesToCache = [ '.', 'index.html' ]`` 
by it 
``let filesToCache = [ 'index.html' ]``

**Comment by GrinOleksandr** [comment]
i added "." before all of my paths in "filesToCache", like: 

> "/index.html"  changes to "./index.html"

and it works for me!!! YEAH!

**Comment by hoangnh0099** [comment]
> i added "." before all of my paths in "filesToCache", like:
> 
> > "/index.html"  changes to "./index.html"
> 
> and it works for me!!! YEAH!

Thanks. It's working

**Comment by hoangnh0099** [comment]
@GrinOleksandr Thanks. It's working

**Comment by aroblesgalit** [comment]
> This happend to me when I had some URL's that I wanted to cache, that did not exist.

Thank you for this comment! I've been trying to figure out why I was having the same issue.

**Comment by buiten-westen** [comment]
me too,  added "." before all of my paths in "filesToCache", like:
"/index.html" changes to "./index.html"
and it works. Way to go!

**Comment by simoncarbajal** [comment]
I'm having the same issue and I can't fix it with the suggestions 😭
