### ISSUE TITLE
script.js gets loaded from ServiceWorker altough it's not referenced in cache.addAll

### ISSUE THREAD

**Issue by justmarkup** [jakearchibald/simple-serviceworker-tutorial#2]
Here is what I did.

1) Made a new folder /sw/1/ on my server justmarkup.com
2) Cloned this repo into the folder /sw/1/
3) Opened /sw/1/simple-serviceworker-tutorial/ in my Browser (Details see below), got console message "This page is not controlled by a ServiceWorker" - Text  "This content was added via JavaScript!" was displayed
4) Reloaded the page, got console message "This page is controlled by a ServiceWorker" - Text "This content was added via JavaScript!" was displayed
5) Opened Devtools, activated Device Mode, set Network to Offline and reloaded the page - Text "This content was added via JavaScript!" was displayed

Browser Details:
I am using Chrome 40 on Ubuntu, more Details about my browser [here](https://justmarkup.com/bugreporter/#:Linux 64-bit:Chrome:40.0.2214.111:Blink:1840 x 969:1920 x 1080:probably landscape:24:16:available:available:enabled:de:1:96dpi, 1dppx, 37.79527559055118dpcm:Mozilla/5.0 %28X11; Linux x86_64%29 AppleWebKit/537.36 %28KHTML, like Gecko%29 Chrome/40.0.2214.111 Safari/537.36:Chrome 40.0.2214.111 on Linux 64-bit)

**Comment by jakearchibald** [comment]
Unfortunately "offline mode" doesn't work with ServiceWorker. See the last paragraph of https://github.com/jakearchibald/simple-serviceworker-tutorial#2-go-offline

**Comment by justmarkup** [comment]
Just tested again, this time switching of my Network completely, still got the same result as described above. Here is my Test-Url: https://justmarkup.com/sw/1/simple-serviceworker-tutorial/
