### ISSUE TITLE
JavaScript-generated text still appears after turning off server

### ISSUE THREAD

**Issue by Trott** [jakearchibald/simple-serviceworker-tutorial#3]
At start:
- Mac OS X running Chrome 40.0.2214.111 (64-bit)
- Unregistered all Service Workers in chrome://serviceworker-internals/ before starting
- Clean checkout of git@github.com:jakearchibald/simple-serviceworker-tutorial.git as cwd/docroot

Actions taken:
- Fire up `http-server -c-1`
- Open `http://localhost:8080`
- Reload 
- Cntl-c to kill `http-server` process
- Reload (soft and hard) page

Expected:
- JS-generated text at bottom of page to be missing.

Actual:
- JS-generated text is still there...

**Comment by Trott** [comment]
Screencast of me going through the above, just in case I'm doing something Horribly Wrong:

https://www.youtube.com/watch?v=Nr8lMtk_txs

**Comment by jakearchibald** [comment]
Thanks for making the screencast! Going to try and recreate…

**Comment by jakearchibald** [comment]
I've added a reset page to the repo, can you check that page out & open it in the browser, then see if Chrome still makes the JS work offline.

Btw, I used to use an image as the item that wouldn't cache, but Chrome was memory caching it. It's entirely possible it's doing it with script too :(

**Comment by Trott** [comment]
That fixed it for me!

**Comment by jakearchibald** [comment]
Did you ever add the script to the cache?

ServiceWorker caches are origin-level like localstorage and indexedDB. If you add stuff to them, they're there until you remove them, even if the ServiceWorker updates or even unregisters.

Even though this makes caches like all other browser storage, this catches everyone out. I should add an exercise that makes this clear.

**Comment by jakearchibald** [comment]
https://github.com/jakearchibald/simple-serviceworker-tutorial/issues/4 could solve this for others
